version: '3'
services:
  app:
    build: .
    command: /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root
    volumes:
      - ./homework:/opt/notebooks
    ports:
      - "8888:8888"
